# Generated by Django 4.0.4 on 2024-03-19 16:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='uploads')),
                ('disease', models.CharField(blank=True, default='None', max_length=500)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='uploads')),
                ('name', models.CharField(blank=True, default='name here', max_length=500)),
                ('email', models.EmailField(blank=True, default='me@mail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+234 081 5566 6644', max_length=500)),
                ('address', models.TextField(blank=True, default='address')),
                ('designation', models.CharField(blank=True, default='consultant', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='me@mail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+234 081 5566 6644', max_length=500)),
                ('occupation', models.CharField(blank=True, default='Farmer', max_length=500)),
                ('name', models.CharField(blank=True, default='Name here', max_length=500)),
                ('farm_name', models.CharField(blank=True, default='Farm name here', max_length=500)),
                ('farm_location', models.CharField(blank=True, default='Farm location', max_length=500)),
                ('office_address', models.CharField(blank=True, default='Office address', max_length=500)),
                ('position', models.CharField(blank=True, default='position at the office', max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='secondary_diagnosis_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, default=None, null=True)),
                ('monday_stop', models.TimeField(blank=True, default=None, null=True)),
                ('tuesday_start', models.TimeField(blank=True, default=None, null=True)),
                ('tuesday_stop', models.TimeField(blank=True, default=None, null=True)),
                ('wednessday_start', models.TimeField(blank=True, default=None, null=True)),
                ('wednessday_stop', models.TimeField(blank=True, default=None, null=True)),
                ('thursday_start', models.TimeField(blank=True, default=None, null=True)),
                ('thursday_stop', models.TimeField(blank=True, default=None, null=True)),
                ('friday_start', models.TimeField(blank=True, default=None, null=True)),
                ('friday_stop', models.TimeField(blank=True, default=None, null=True)),
                ('diagnosis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, default='no diagnosis')),
                ('prescription', models.TextField(blank=True, default='no treatment')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('member', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.member')),
                ('crops_farmed', models.TextField(blank=True, default='crops farmed')),
                ('farm_location', models.TextField(blank=True, default='farm location')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='lab_attendant',
            fields=[
                ('member', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.member')),
                ('lab_specialization', models.TextField(blank=True, default='lab specialization')),
                ('lab_location', models.TextField(blank=True, default='lab location')),
                ('longitude', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='uploads')),
                ('done', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='None', max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='secondary_diagnosis_lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_visit_day', models.CharField(blank=True, default='day here', max_length=500)),
                ('diagnosis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.diagnosis')),
                ('secondary_diagnosis_farmer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.secondary_diagnosis_farmer')),
                ('lab_attendant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.lab_attendant')),
            ],
        ),
        migrations.CreateModel(
            name='new_treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_diagnosis', models.TextField(blank=True, default='no diagnosis')),
                ('new_prescription', models.TextField(blank=True, default='no treatment')),
                ('secondary_diagnosis_farmer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.secondary_diagnosis_farmer')),
                ('secondary_diagnosis_lab', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.secondary_diagnosis_lab')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='TaskImage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.taskimage'),
        ),
        migrations.AddField(
            model_name='secondary_diagnosis_farmer',
            name='farmer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.farmer'),
        ),
    ]
