# Generated by Django 4.0.4 on 2024-03-19 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='message here')),
                ('likes', models.TextField(blank=True, default='message here')),
                ('picture', models.ImageField(blank=True, upload_to='uploads')),
                ('youtube_video', models.CharField(blank=True, default='None', max_length=1000)),
                ('sound', models.FileField(blank=True, upload_to='uploads')),
                ('comment', models.TextField(blank=True, default='no comment')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 19, 16, 55, 2, 793148, tzinfo=utc))),
            ],
        ),
    ]
