# Generated by Django 4.0.4 on 2024-03-23 11:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_chat_date_alter_diagnosis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='TaskImage',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='label',
            field=models.CharField(blank=True, default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 23, 11, 5, 28, 133434, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TaskImage',
        ),
    ]
