# Generated by Django 4.0.4 on 2024-03-23 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diagnosis_done_alter_chat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 13, 18, 46, 191005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 23, 13, 18, 46, 198197, tzinfo=utc)),
        ),
    ]
