# Generated by Django 4.0.4 on 2024-07-05 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_diagnosis_date_alter_chat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='title',
            field=models.CharField(blank=True, default='treatment', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 5, 18, 15, 26, 693136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 18, 15, 26, 686978, tzinfo=utc)),
        ),
    ]
